apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   # At most 1 pod can be unavailable during update
      maxSurge: 1         # At most 1 extra pod can be created temporarily
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        #image: PLACEHOLDER
        image: 205842488113.dkr.ecr.ap-south-1.amazonaws.com/fastapi-app:IMAGE_TAG
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "400m"


